# Set the version of docker compose to use
version: "3.9"

# The containers that compose the project
services:
  db-dev:
    image: postgres:latest
    restart: always
    container_name: db-dev
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-test:
    image: postgres:latest
    container_name: db-test
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests

volumes:
  pgdata:
